[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 30

[[services]]
name = "frontend"
port = 3000

[environments.production]
NODE_ENV = "production"
# Frontend will use its own API routes, not external backend